"""Novedades del bot: de la lista que deja el NAS a las notas de cada PR.

`actualizar.sh` deja en el buzón una línea por cambio desplegado (ver
`bot.services.deploy`). Cada línea lleva cuatro campos separados por
tabuladores: `#número`, `dueño/rama` de origen del PR, `titulo` o `commit`, y
el texto. Las de tipo `commit` salen de PR cuyo título es el que GitHub pone
solo con el nombre de la rama: el texto es el asunto de cada commit. Una línea
sin tabuladores es el formato anterior (solo el título) y se acepta igual: el
despliegue que trae este código lo apunta todavía el script viejo.

Con el número y la rama, `fetch_pulls` pide a la API pública de GitHub la
descripción, el autor y el enlace de cada PR, como en la página del PR. El
número no dice de qué repositorio es: los PR del fork llegan a `main` junto a
los del repositorio del bot. Se prueba en cada uno de `REPOS` y vale el que
tenga la misma rama de origen. Si GitHub no responde, el aviso sale solo con
los títulos.

Este módulo no depende de discord.py; el aviso lo monta `bot.cogs.deploy`.
"""

from __future__ import annotations

import logging
import re
from collections.abc import Awaitable, Callable, Mapping
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any

import aiohttp

logger = logging.getLogger(__name__)

#: Repositorios donde buscar cada PR, en orden: el que se despliega y su fork
#: (ver «Dos repositorios» en CLAUDE.md).
REPOS: tuple[str, ...] = (
    "godzilin/Proyecto_BOT_JovaniVazquez",
    "Yeyo-Yeyex/Proyecto_BOT_JovaniVazquez_forkyeyo",
)
API_URL = "https://api.github.com/repos/{repo}/pulls/{number}"
#: Segundos que se espera a GitHub por petición.
TIMEOUT_SECONDS = 10

_LINE = re.compile(r"^#(?P<number>\d+)\t(?P<head>[^\t]+)\t(?P<kind>titulo|commit)\t(?P<text>.+)$")
_HEADING = re.compile(r"^#{1,6}\s+(?P<text>.+?)\s*#*$", re.MULTILINE)
_COMMENT = re.compile(r"<!--.*?-->", re.DOTALL)
#: Líneas de firma que añade Claude Code al final de los PR; no aportan nada al aviso.
_SIGNATURE = re.compile(
    r"^\s*(🤖 Generated with .*|_Generated by .*_|https://claude\.ai/code/\S+)\s*$", re.MULTILINE
)

#: Cómo se pide un PR: `(repo, número)` → JSON de la API, o `None` si no existe.
Fetch = Callable[[str, int], Awaitable[Mapping[str, Any] | None]]


@dataclass(slots=True)
class NewsItem:
    """Un cambio desplegado, tal como lo apuntó `actualizar.sh`.

    Attributes:
        title: Título del PR; `None` si solo se conocen sus commits.
        number: Número del PR; `None` en el formato antiguo.
        head: Rama de origen como `dueño/rama`; `None` en el formato antiguo.
        commits: Asuntos de los commits cuando el PR no tiene título propio.
    """

    title: str | None
    number: int | None = None
    head: str | None = None
    commits: list[str] = field(default_factory=list)

    @property
    def headline(self) -> str:
        """Lo que se enseña como título: el del PR o sus commits."""
        return self.title or "; ".join(self.commits)


@dataclass(frozen=True, slots=True)
class PullRequest:
    """Lo que GitHub cuenta de un PR fusionado."""

    repo: str
    number: int
    url: str
    body: str
    author: str | None
    author_url: str | None
    author_avatar: str | None
    merged_at: datetime | None


@dataclass(slots=True)
class NewsEntry:
    """Un cambio del aviso con lo que se sepa de su PR (nada si GitHub no respondió)."""

    item: NewsItem
    pull: PullRequest | None = None


def parse_news(lines: list[str]) -> list[NewsItem]:
    """Agrupa las líneas del buzón en cambios, en el orden en que llegaron.

    Los commits seguidos de un mismo PR forman un solo cambio.
    """
    items: list[NewsItem] = []
    for raw in lines:
        line = raw.strip()
        if not line:
            continue
        match = _LINE.match(line)
        if match is None:
            items.append(NewsItem(title=line))
            continue
        number, head, text = int(match["number"]), match["head"], match["text"].strip()
        if match["kind"] == "titulo":
            items.append(NewsItem(title=text, number=number, head=head))
            continue
        last = items[-1] if items else None
        if last is not None and last.title is None and (last.number, last.head) == (number, head):
            last.commits.append(text)
        else:
            items.append(NewsItem(title=None, number=number, head=head, commits=[text]))
    return items


def clean_body(body: str | None) -> str:
    """Descripción de un PR lista para Discord.

    Quita comentarios HTML y la firma de Claude Code, y pasa los encabezados
    de Markdown a negrita, que Discord pinta igual en todas partes.
    """
    text = _COMMENT.sub("", body or "").replace("\r\n", "\n")
    text = _SIGNATURE.sub("", text)
    text = _HEADING.sub(lambda m: f"**{m['text']}**", text)
    text = re.sub(r"\n{3,}", "\n\n", text).strip()
    # Lo que queda tras la firma suele ser una raya `---` suelta.
    while text.endswith("---"):
        text = text[:-3].rstrip()
    return text


def _parse_pull(repo: str, data: Mapping[str, Any]) -> PullRequest:
    user = data.get("user") or {}
    merged = data.get("merged_at")
    return PullRequest(
        repo=repo,
        number=int(data["number"]),
        url=str(data.get("html_url") or f"https://github.com/{repo}/pull/{data['number']}"),
        body=clean_body(data.get("body")),
        author=user.get("login"),
        author_url=user.get("html_url"),
        author_avatar=user.get("avatar_url"),
        merged_at=datetime.fromisoformat(merged.replace("Z", "+00:00")) if merged else None,
    )


def _same_head(data: Mapping[str, Any], head: str) -> bool:
    """Si el PR de GitHub sale de la rama `dueño/rama` que apuntó el script."""
    label = str((data.get("head") or {}).get("label") or "")
    return label.lower() == head.replace("/", ":", 1).lower()


async def find_pull(
    item: NewsItem, fetch: Fetch, repos: tuple[str, ...] = REPOS
) -> PullRequest | None:
    """Busca el PR de un cambio en `repos`; `None` si no está o GitHub falla."""
    if item.number is None or item.head is None:
        return None
    for repo in repos:
        data = await fetch(repo, item.number)
        if data is not None and _same_head(data, item.head):
            return _parse_pull(repo, data)
    return None


async def fetch_pulls(items: list[NewsItem], fetch: Fetch) -> list[NewsEntry]:
    """Completa cada cambio con su PR de GitHub, si se encuentra."""
    return [NewsEntry(item, await find_pull(item, fetch)) for item in items]


def github_fetcher(session: aiohttp.ClientSession) -> Fetch:
    """`Fetch` contra la API pública de GitHub (sin token: 60 peticiones/hora).

    Cualquier error (red, límite, PR inexistente) da `None` y queda en el log:
    el aviso sale igual, con menos detalle.
    """
    timeout = aiohttp.ClientTimeout(total=TIMEOUT_SECONDS)
    headers = {"Accept": "application/vnd.github+json", "User-Agent": "bot-jovani-vazquez"}

    async def fetch(repo: str, number: int) -> Mapping[str, Any] | None:
        url = API_URL.format(repo=repo, number=number)
        try:
            async with session.get(url, headers=headers, timeout=timeout) as response:
                if response.status == 404:
                    return None
                if response.status != 200:
                    logger.warning("GitHub respondió %s a %s", response.status, url)
                    return None
                return await response.json()
        except (aiohttp.ClientError, TimeoutError, ValueError):
            logger.warning("No se pudo pedir %s a GitHub", url, exc_info=True)
            return None

    return fetch
