"""Pruebas de las novedades del bot: leer el buzón, buscar cada PR en GitHub
(bot.services.changelog) y guardar los ajustes de `cambios`
(bot.repositories.news y el comando del cog Admin)."""

from __future__ import annotations

from pathlib import Path
from types import SimpleNamespace
from unittest.mock import AsyncMock, MagicMock

import discord
import pytest

from bot.cogs.admin import CHANNEL_REFERENCE, Admin
from bot.repositories.news import NewsRepository, NewsSettings
from bot.services.changelog import REPOS, NewsItem, clean_body, find_pull, parse_news

GODZILIN, FORK = REPOS


def test_lee_titulos_y_agrupa_los_commits_de_un_mismo_pr() -> None:
    lines = [
        "#1\tyeyo/pollo\ttitulo\tPollo: carriles más rápidos",
        "#2\tyeyo/claude/x\tcommit\tMascotas",
        "#2\tyeyo/claude/x\tcommit\tMás mascotas",
        "",
        "Título del formato antiguo",
    ]

    items = parse_news(lines)

    assert items == [
        NewsItem("Pollo: carriles más rápidos", 1, "yeyo/pollo"),
        NewsItem(None, 2, "yeyo/claude/x", ["Mascotas", "Más mascotas"]),
        NewsItem("Título del formato antiguo"),
    ]
    assert items[1].headline == "Mascotas; Más mascotas"


def test_la_descripcion_pierde_la_firma_y_los_comentarios() -> None:
    body = (
        "<!-- plantilla -->\r\n## Qué cambia\r\nLos caballos corren.\r\n\r\n\r\n"
        "🤖 Generated with [Claude Code](https://claude.com/claude-code)\n\n"
        "https://claude.ai/code/session_01ABC\n\n---\n"
        "_Generated by [Claude Code](https://claude.ai/code/session_01ABC)_"
    )

    assert clean_body(body) == "**Qué cambia**\nLos caballos corren."
    assert clean_body(None) == ""


def _github(head: str, number: int = 5) -> dict:
    return {
        "number": number,
        "html_url": f"https://github.com/x/pull/{number}",
        "body": "Cuerpo",
        "user": {"login": "Yeyo-Yeyex", "html_url": "https://github.com/Yeyo-Yeyex"},
        "head": {"label": head},
        "merged_at": "2026-10-10T16:04:47Z",
    }


@pytest.mark.asyncio
async def test_el_pr_se_busca_en_el_repo_cuya_rama_coincide() -> None:
    """El mismo número existe en los dos repos; vale el que sale de la rama apuntada."""
    answers = {
        (GODZILIN, 6): _github("Yeyo-Yeyex:main", 6),
        (FORK, 6): _github("Yeyo-Yeyex:claude/ruleta", 6),
    }

    async def fetch(repo: str, number: int) -> dict | None:
        return answers.get((repo, number))

    pull = await find_pull(NewsItem("Ruleta", 6, "Yeyo-Yeyex/claude/ruleta"), fetch)

    assert pull is not None
    assert pull.repo == FORK
    assert pull.author == "Yeyo-Yeyex"
    assert pull.merged_at is not None and pull.merged_at.year == 2026


@pytest.mark.asyncio
async def test_sin_numero_o_sin_respuesta_no_hay_pr() -> None:
    fetch = AsyncMock(return_value=None)

    assert await find_pull(NewsItem("Antiguo"), fetch) is None
    fetch.assert_not_awaited()
    assert await find_pull(NewsItem("Nuevo", 3, "yeyo/rama"), fetch) is None


# -- Ajustes y comando `cambios` ----------------------------------------------------------


@pytest.mark.asyncio
async def test_los_ajustes_se_guardan_y_se_borran(tmp_path: Path) -> None:
    repository = NewsRepository(tmp_path / "bot.sqlite3")
    await repository.initialize()

    assert await repository.settings(1) == NewsSettings()
    await repository.save_settings(1, NewsSettings(enabled=False, channel_id=7, detailed=False))
    assert await repository.settings(1) == NewsSettings(False, 7, False)

    await repository.delete_guild_data(1)
    assert await repository.settings(1) == NewsSettings()


def _admin_with_repository(tmp_path: Path) -> tuple[Admin, NewsRepository]:
    repository = NewsRepository(tmp_path / "bot.sqlite3")
    bot = MagicMock()
    bot.news = repository
    return Admin(bot), repository


def _thread(channel_id: int, *, can_write: bool = True) -> MagicMock:
    thread = MagicMock(spec=discord.Thread)
    thread.id = channel_id
    thread.mention = f"<#{channel_id}>"
    thread.locked = False
    thread.permissions_for.return_value = discord.Permissions(send_messages_in_threads=can_write)
    return thread


def _responder(*, cached: dict | None = None, api: dict | None = None) -> SimpleNamespace:
    """Servidor con `#chat-general`, lo que tiene en caché y lo que da la API."""
    general = MagicMock(spec=discord.TextChannel)
    general.name = "chat-general"
    general.mention = "#chat-general"
    guild = MagicMock(spec=discord.Guild)
    guild.id = 1
    guild.text_channels = [general]
    guild.get_channel_or_thread = lambda channel_id: (cached or {}).get(channel_id)

    async def fetch_channel(channel_id: int) -> object:
        if channel_id not in (api or {}):
            raise discord.NotFound(MagicMock(status=404), "Unknown Channel")
        return api[channel_id]

    guild.fetch_channel = fetch_channel
    return SimpleNamespace(guild=guild, send=AsyncMock(), send_error=AsyncMock())


@pytest.mark.asyncio
async def test_cambios_sin_argumentos_ensena_la_configuracion(tmp_path: Path) -> None:
    admin, repository = _admin_with_repository(tmp_path)
    await repository.initialize()
    responder = _responder()

    await admin._cambios_impl(responder, None, None)

    text = responder.send.await_args.args[0]
    assert "se publica" in text and "detallado" in text and "#chat-general" in text
    assert responder.send.await_args.kwargs["ephemeral"] is True


@pytest.mark.asyncio
async def test_cambios_apaga_y_pasa_a_resumen(tmp_path: Path) -> None:
    admin, repository = _admin_with_repository(tmp_path)
    await repository.initialize()
    canal = MagicMock(spec=discord.TextChannel)
    canal.id = 9
    responder = _responder(cached={9: canal})

    await admin._cambios_impl(responder, "desactivar", 9)
    await admin._cambios_impl(responder, "resumen", None)

    responder.send_error.assert_not_awaited()
    assert await repository.settings(1) == NewsSettings(enabled=False, channel_id=9, detailed=False)

    await admin._cambios_impl(_responder(), "defecto", None)
    assert (await repository.settings(1)).channel_id is None


@pytest.mark.asyncio
async def test_cambios_acepta_un_hilo_archivado(tmp_path: Path) -> None:
    """Un hilo archivado no está en la caché: se pide a Discord y vale igual."""
    admin, repository = _admin_with_repository(tmp_path)
    await repository.initialize()
    hilo = _thread(55)
    responder = _responder(api={55: hilo})

    await admin._cambios_impl(responder, None, 55)

    responder.send_error.assert_not_awaited()
    assert (await repository.settings(1)).channel_id == 55
    text = responder.send.await_args.args[0]
    assert "Canal: <#55>" in text and "No puedo escribir" not in text


@pytest.mark.asyncio
async def test_cambios_avisa_si_no_puede_escribir_en_el_hilo(tmp_path: Path) -> None:
    admin, repository = _admin_with_repository(tmp_path)
    await repository.initialize()
    responder = _responder(cached={55: _thread(55, can_write=False)})

    await admin._cambios_impl(responder, None, 55)

    assert "No puedo escribir ahí" in responder.send.await_args.args[0]


@pytest.mark.asyncio
async def test_cambios_rechaza_un_canal_que_no_existe(tmp_path: Path) -> None:
    admin, repository = _admin_with_repository(tmp_path)
    await repository.initialize()
    responder = _responder()

    await admin._cambios_impl(responder, None, 404)

    responder.send_error.assert_awaited_once()
    assert await repository.settings(1) == NewsSettings()


@pytest.mark.asyncio
async def test_cambios_no_acepta_canal_y_defecto_a_la_vez(tmp_path: Path) -> None:
    admin, repository = _admin_with_repository(tmp_path)
    await repository.initialize()
    responder = _responder()

    await admin._cambios_impl(responder, "defecto", 9)

    responder.send_error.assert_awaited_once()
    assert await repository.settings(1) == NewsSettings()


def test_el_slash_acepta_hilos_aunque_no_esten_en_la_cache() -> None:
    """La opción `canal` ofrece hilos y no exige que el bot los tenga en memoria."""
    (canal,) = [p for p in Admin.cambios.parameters if p.name == "canal"]

    assert discord.ChannelType.public_thread in canal.channel_types
    assert discord.ChannelType.private_thread in canal.channel_types
    assert discord.ChannelType.text in canal.channel_types


@pytest.mark.parametrize(
    ("arg", "expected"),
    [("<#123456789012345678>", 123456789012345678), ("123456789012345678", 123456789012345678)],
)
def test_cambios_de_texto_reconoce_hilos_por_mencion_o_id(arg: str, expected: int) -> None:
    """Un hilo archivado no lo encuentran los conversores; su mención o ID sí valen."""
    match = CHANNEL_REFERENCE.fullmatch(arg)

    assert match is not None and int(match[1] or match[2]) == expected
    assert CHANNEL_REFERENCE.fullmatch("anuncios") is None
